### ISSUE TITLE
Outdated and incomplete guidelines

### ISSUE THREAD

**Issue by thiagodefreitas** [synapticon/Synapticon-Coding-Style-Guide#2]
When discussing with @cyborg-x1 , @Minipada , @jfilba ,@luator, @alireza-hosseini we have found some inconsistencies among the xC code base. 

It is also not properly described how the things that are not defined on the xC guideline should be handled.

e.g. Should we apply the C/C++ guideline to the **Conditional statements** on xC?

The current C/C++ guideline seems to be outdated, since it does not follow the Google one anymore. Also, there are some internal divergences. Could we please discuss it a bit and get to an agreement and have it merged on both guidelines?

**Comment by cyborg-x1** [comment]
The biggest point of discussion was the indentation:

Where a majority in our team favored the Allman style of indentation (4 vs 2) :
```
if(condition)
{
  func();
  func2();
}
else
{
   ....
}
```

https://en.wikipedia.org/wiki/Indent_style#Allman_style

Consequences of this style are that the indented code is clearly set apart from the containing statement by lines that are almost all whitespace and the closing brace lines up in the same column as the opening brace. This makes it easy to find matching braces. The blocking style also delineates the block of code from the associated control statement. Commenting out or removing a control statement or block of code, or code refactoring, are all less likely to introduce syntax errors via dangling or missing braces. Also, it is consistent with brace placement for the outer-function block.

instead of
```

if(condition){
  func();
  func2();
}else{
  ....
}
```
Which just safes 1 to 3 lines. As far as I remembered in a meeting we actually agreed on the Allman one. -> Clearer code. So I wonder why it is different in this document.

**Comment by fjes** [comment]
@thiagodefreitas 
1. As we created the Coding Style guidelines we agreed on applying the C/C++ Coding Style plus xC specifics which are described in the second file. I agree we could make it more clear in the xC document that for everything not xC specific the default C/C++ is mandatory.

2. I don't see something bad in getting some distance to the google guidelines, IMO they are also not perfect.

@cyborg-x1 in my opinion the second example is favourable. Because it safes on line vertical space at every loop and conditional. I'm used to read code like this and I don't have problems finding the matching brace if the code is otherwise properly formatted. Especially if no 128 character variable/function names are used in the misguided thinking this were descriptive.

Currently I see Coding Style discussions like Space vs. Tabs, starting curly brace position etc. are more of religious content. It's maybe better to stick to the default XMOS style thing for xC code and don't waste too much time discussing about the most sane way to format the code. My 2ct.

**Comment by jfilba** [comment]
@fjes What do you mean by `default XMOS style thing for xC code`? Could you add a link to it?

**Comment by thiagodefreitas** [comment]
@fjes For your replies to my questions, I completely agree to you. And I can make it clearer that whatever is not defined on the xC guide should follow the C/C++, we just needed the agreement from the **other room**.

Also, on the C/C++ guide there are a lot of misplaced backslash characters, such as in ```FOO\_BAR\_BAZ\_H\_```, which is not a problem for me to fix also.

I also agree that this does not need to be an extent discussion as actually in the end some beautifier is going to take care of applying the style to the code, but we just need that it is properly agreed and defined there. 

So, my main idea is just that we at least once in a lifetime read the guide and check for errors or misleading information, so that it is set, because we need it for our code at the moment, and cannot keep changing it.

**Comment by fjes** [comment]
![screen shot 2017-07-25 at 16 22 03](https://user-images.githubusercontent.com/826421/28576891-75af8974-7155-11e7-9c16-0e6977cbefaa.png)

@jfilba I mean the build-in XMOS profile. There is as far as I know no more description than the xml for the XTC profile.

**Comment by fjes** [comment]
@thiagodefreitas And in my opinion this is exactly the problem. Every now and then a developer with a strong opinion comes along and wants the braces differently or the CamelCase starting upper case. My intention in propose the XMOS built-in default was to minimise complains  - nobody has to think or kick in a sanitizer - just type ;)

For some version of the file these escapes '\' were necessary at some point, but know they are obsolete. Would be nice if you could remove them.

**Comment by luator** [comment]
@thiagodefreitas I already removed the backslashes in PR #3.

**Comment by thiagodefreitas** [comment]
Solved by changes in the guidelines, discussions, clang-format and a bit of common sense.
